config/routes.rb
Campusvideo::Application.routes.draw do
  resources :videos

  resources :courses

  resources :packages

  resources :areas

  resources :descriptions

  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

app/models/description.rb
class Description < ActiveRecord::Base
  has_one :user
  attr_accessible :address, :information, :name, :phone, :picture, :user
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  before_filter :authenticate_user!
  # GET /descriptions
  # GET /descriptions.json
  def index
    @descriptions = Description.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @descriptions }
    end
  end

  # GET /descriptions/1
  # GET /descriptions/1.json
  def show
    @description = Description.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @description }
    end
  end

  # GET /descriptions/new
  # GET /descriptions/new.json
  def new
    @description = Description.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @description }
    end
  end

  # GET /descriptions/1/edit
  def edit
    @description = Description.find(params[:id])
  end

  # POST /descriptions
  # POST /descriptions.json
  def create
    @description = Description.new(params[:description])

    respond_to do |format|
      if @description.save
        user = current_user
        user.description = @description
        user.save
        format.html { redirect_to @description, notice: 'Description was successfully created.' }
        format.json { render json: @description, status: :created, location: @description }
      else
        format.html { render action: "new" }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /descriptions/1
  # PUT /descriptions/1.json
  def update
    @description = Description.find(params[:id])

    respond_to do |format|
      if @description.update_attributes(params[:description])
        format.html { redirect_to @description, notice: 'Description was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /descriptions/1
  # DELETE /descriptions/1.json
  def destroy
    @description = Description.find(params[:id])
    @description.destroy

    respond_to do |format|
      format.html { redirect_to descriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/views/descriptions/_form.html.erb
<%= form_for(@description, :html => {:class=>'form-horizontal'}) do |f| %>
  <% if @description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@description.errors.count, "error") %> prohibited this description from being saved:</h2>

      <ul>
      <% @description.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span5">
      <div class="field">
        <%= f.label :name, "nome" %><br />
        <%= f.text_field :name, :style => 'width:100%' %>
      </div>
      <!-- div class="field">
        <%= f.label :picture %><br />
        <%= f.text_field :picture, :style => 'width:100%' %>
      </div -->
      <div class="field">
        <%= f.label :address, "endereço" %><br />
        <%= f.text_field :address, :style => 'width:100%' %>
      </div>
      <div class="field">
        <%= f.label :phone, "telefone" %><br />
        <%= f.text_field :phone, :style => 'width:100%' %>
      </div>
    </div>
    <div class="span1"></div>
    <div class="span5">
      <div class="field">
        <%= f.label :information, "informações" %><br />
        <%= f.text_area :information, :style => 'width:100%; height: 185px' %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "salvar" %>
  </div>
<% end %>

app/views/descriptions/edit.html.erb
<h1>Editing description</h1>

<%= render 'form' %>

<%= link_to 'Show', @description %> |
<%= link_to 'Back', descriptions_path %>

app/views/descriptions/index.html.erb
<h1>Listing descriptions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Picture</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Information</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @descriptions.each do |description| %>
  <tr>
    <td><%= description.name %></td>
    <td><%= description.picture %></td>
    <td><%= description.address %></td>
    <td><%= description.phone %></td>
    <td><%= description.information %></td>
    <td><%= link_to 'Show', description %></td>
    <td><%= link_to 'Edit', edit_description_path(description) %></td>
    <td><%= link_to 'Destroy', description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Description', new_description_path %>

app/views/descriptions/new.html.erb
<h3>Configure sua Conta</h3>

<div class="span12">
<%= render 'form' %>
</div>

app/views/descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>nome:</b>
  <%= @description.name %>
</p>

<p>
  <b>email:</b>
  <%= @description.user.email %>
</p>

<!--p>
  <b>Picture:</b>
  <%= @description.picture %>
</p-->

<!--p>
  <b>Address:</b>
  <%= @description.address %>
</p-->

<p>
  <b>telefone:</b>
  <%= @description.phone %>
</p>

<p>
  <b>informações:</b>
  <%= @description.information %>
</p>