config/routes.rb
Campusvideo::Application.routes.draw do
  resources :videos

  resources :courses

  resources :packages

  resources :areas

  resources :descriptions

  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  has_and_belongs_to_many :buyers,
    :class_name => 'User',
    :join_table => 'users_videos',
    :foreign_key => 'video_id',
    :association_foreign_key => 'user_id',
    :uniq => true
  attr_accessible :information, :name, :panda_video, 
  :panda_video_id, :price, :user, :course, :course_id, :buyers, :user_id

  def panda_video
    @panda_video ||= Panda::Video.find(panda_video_id)
  end

  def self.video_by_user_permission video_id, user_id
    @video = self.all(
      :include => :buyers,
      :conditions => [
        "users.id = ? AND videos.id = ?",
        user_id,
        video_id
      ]
    )

    if @video.empty?
      @video = self.find_by_id_and_user_id(video_id,user_id)
    else
      @video = @video.first
    end

    @video
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!
  layout 'ajax', :only => 'showjs'
  # GET /videos
  # GET /videos.json
  def index
    @videos = current_user.videos
    @purchased_videos = current_user.purchased_videos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    if params.has_key? :id
      @video_id = params[:id]
    else
      redirect_to home_index_path, :alert => "Pagina inexistente."
      return
    end

    if !current_user.is_admin?
      @video = Video.video_by_user_permission @video_id, current_user.id
    else
      @video = Video.find @video_id
    end
    
    if !@video
      redirect_to home_index_path, :alert => "Video sem permissao."
      return
    end

    @original_video = @video.panda_video
    @h264_encoding = @original_video.encodings["h264"]

    @owner = false
    @owner = true if @video.user.id == current_user.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end


  # GET /videos/new
  # GET /videos/new.json
  def new
    if !current_user.can_add_courses?
      redirect_to home_index_path, :alert => "Atividade bloqueada"
      return
    end

    if !current_user.is_admin?
      @course = Course.find_by_id_and_user_id(params[:course],current_user.id)
    else
      @course = Course.find params[:course]
    end

    if @course.nil?
      redirect_to home_index_path, :alert => "Sem permissao para editar"
      return
    end

    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= javascript_include_tag "jquery.panda-uploader.min.js" %>
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="span6">
      <div class="field">
        <%= f.label :name, 'título' %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :information, 'informações' %><br />
        <%= f.text_area :information %>
      </div>
    </div>

    <div class="span6">
      <div class="field">
        <%= f.label :price, 'preço (R$)' %><br />
        <%= f.number_field :price, :min => 0, :value => 0 %>
      </div>
      <%= f.hidden_field :course_id, :value => @course.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="field">
        <%= f.label "video" %><br />
        <%= f.hidden_field :panda_video_id, {:id => "returned_video_id"} %>
      </div> <br />
      <div class="field">
        <div id="upload_progress" class="panda_upload_progress"></div>
      </div>
      <div class="actions">
        <%= f.submit "salvar" %>
      </div>
    </div>

  </div>

<% end %>
<script>
  <% auth_params = Panda.signed_params('post', "/videos.json") %>
  jQuery("#returned_video_id").pandaUploader(<%=raw auth_params.to_json %>, {
    // Uncomment the line below if your panda account is in the EU
    // api_host: 'api-eu.pandastream.com',
    upload_progress_id: 'upload_progress'
  });
</script>

app/views/videos/_view.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :information %><br />
    <%= f.text_area :information %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :panda_video_id %><br />
    <%= f.text_field :panda_video_id %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="container">
<% if !@videos.empty? %>
<h3>Meus Vídeos</h3>
  <ul class="thumbnails">
    <% @videos.each do |video| %>
      <li class="span3">
        <a href="videos/<%= video.id %>" class="thumbnail thumb-video">
          <img class="img-rounded" src="<%= video.panda_video.encodings["h264"].screenshots.first %>" alt="">
          <b><%= video.name %></b><br>
          <%= video.information %><br>
          <%= video.course.name if video.course %>
          <%= video.user.description.name if video.user.description %>
        </a>
      </li>
    <% end %>
  </ul>
<% end %>


<% if !@purchased_videos.empty? %>
  <h3>Vídeos Adiquiridos</h3>
  <ul class="thumbnails">
    <% @purchased_videos.each do |video| %>
      <li class="span3">
        <a href="videos/<%= video.id %>" class="thumbnail thumb-video">
          <img class="img-rounded" src="<%= video.panda_video.encodings["h264"].screenshots.first %>" alt="">
          <b><%= video.name %></b><br>
          <%= video.information %><br>
          <%= video.course.name if video.course %>
          <%= "professor: #{video.user.description.name}<br>".html_safe if video.user.description %>
        </a>
      </li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/videos/new.html.erb
<div class='container'>
<h1>Novo Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>
</div>

app/views/videos/show.html.erb
<div class="container">
<h3><%= @video.name %></h3>
<p id="notice"><%= notice %></p>
<p>
<div id='flash_player'>Flash player will appear here</div>
<script type='text/javascript'>
    jwplayer("flash_player").setup({
        file: "<%= @h264_encoding.url %>",
        width: "100%",
        height: "400px",
        image: "<%= @h264_encoding.screenshots.first %>",
    });
</script>
</p>

<p>
  <b>informações:</b>
  <%= @video.information %>
</p>

<% if @video.course %>
<p>
  <b>curso:</b>
  <%= link_to @video.course.name, @video.course %>
</p>
<% end %>

<% if @video.user %>
<p>
  <b>professor:</b>
  <%= link_to @video.user.description.name, @video.user.description %>
</p>
<% end %>
</div>