config/routes.rb
Campusvideo::Application.routes.draw do
  resources :videos

  resources :courses

  resources :packages

  resources :areas

  resources :descriptions

  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :courses
  attr_accessible :information, :name, :courses
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_filter :authenticate_user!
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :information %><br />
    <%= f.text_area :information %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="span3">

<%= link_to 'New Area', new_area_path %>
      <table>
        <tr>
          <th>Name</th>
          <th>Information</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @areas.each do |area| %>
          <tr>
            <td><%= area.name %></td>
            <td><%= area.information %></td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="span6">
      <p>OADoaGD OA DgoadgO doP DgDpg</p>
    </div>
    
    <div class="span3">
      eaodboabdgad adioa gadg aodigh agoadghioahgoadgh aodgi adg aodgih adoi 
    </div>
  </div>
</div>

<br />

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @area.name %>
</p>

<p>
  <b>Information:</b>
  <%= @area.information %>
</p>


<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>